name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Install dependencies
      run: |
        cd PuppetBotClient
        dotnet restore
    - name: Build
      run: |
        cd PuppetBotClient
        dotnet build --configuration Release --no-restore --nologo
    - name: Publish
      run: |
        cd PuppetBotClient
        dotnet publish PuppetBotClient -r win-x86 --configuration Release --nologo -p:PublishSingleFile=true --self-contained true -o ./Publish
        rm ./Publish/*.pdb
        cp ../README.md ./Publish
        cp ../LICENSE ./Publish
        cp ./PuppetBotClient/appsettings.json ./Publish
    - name: Package Release
      run: |
        cd PuppetBotClient
        zip -r PuppetBotClient-x86.zip ./Publish
        ls ./Publish
    - name: Release Package
      uses: svenstaro/upload-release-action@2.2.1
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: ./PuppetBotClient/PuppetBotClient-x86.zip
        tag: Develop
        overwrite: true
